//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TO2_ESEMKA_BAKERY
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class selectiontestwsc2017Entities : DbContext
    {
        public selectiontestwsc2017Entities()
            : base("name=selectiontestwsc2017Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<food> foods { get; set; }
        public virtual DbSet<incomingrawmaterialdetail> incomingrawmaterialdetails { get; set; }
        public virtual DbSet<incomingrawmaterialheader> incomingrawmaterialheaders { get; set; }
        public virtual DbSet<productiondetail> productiondetails { get; set; }
        public virtual DbSet<productionheader> productionheaders { get; set; }
        public virtual DbSet<rawmaterial> rawmaterials { get; set; }
        public virtual DbSet<rawmaterialintake> rawmaterialintakes { get; set; }
        public virtual DbSet<recipedetail> recipedetails { get; set; }
        public virtual DbSet<recipeheader> recipeheaders { get; set; }
        public virtual DbSet<sellingdetail> sellingdetails { get; set; }
        public virtual DbSet<sellingheader> sellingheaders { get; set; }
    }
}
