//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TO2_ESEMKA_BAKERY
{
    using System;
    using System.Collections.Generic;
    
    public partial class productiondetail
    {
        public int productionid { get; set; }
        public int batchnumber { get; set; }
        public int foodid { get; set; }
        public int productionoutputqty { get; set; }
        public System.DateTime expireddate { get; set; }
    
        public virtual food food { get; set; }
        public virtual productionheader productionheader { get; set; }
    }
}
