//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TO2_ESEMKA_BAKERY
{
    using System;
    using System.Collections.Generic;
    
    public partial class productionheader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public productionheader()
        {
            this.productiondetails = new HashSet<productiondetail>();
        }
    
        public int productionid { get; set; }
        public System.DateTime productiondate { get; set; }
        public string description { get; set; }
        public int employeeid { get; set; }
        public string status { get; set; }
    
        public virtual employee employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<productiondetail> productiondetails { get; set; }
    }
}
