//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TO2_ESEMKA_BAKERY
{
    using System;
    using System.Collections.Generic;
    
    public partial class recipeheader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public recipeheader()
        {
            this.recipedetails = new HashSet<recipedetail>();
        }
    
        public int recipeid { get; set; }
        public int foodid { get; set; }
        public int outputunitinpieces { get; set; }
        public string description { get; set; }
        public int employeeid { get; set; }
        public System.DateTime createddate { get; set; }
        public string status { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual food food { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<recipedetail> recipedetails { get; set; }
    }
}
