//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TO2_ESEMKA_BAKERY
{
    using System;
    using System.Collections.Generic;
    
    public partial class sellingdetail
    {
        public int sellingid { get; set; }
        public int foodid { get; set; }
        public int batchnumber { get; set; }
        public int qty { get; set; }
        public int price { get; set; }
    
        public virtual food food { get; set; }
        public virtual sellingheader sellingheader { get; set; }
    }
}
